version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    ports:
      - "8000:8000"
